config/routes.rb
Rails.application.routes.draw do
  resources :products, only: [:index, :show]
  resources :companies, only: [:index, :show]
  resources :ingredients, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_and_belongs_to_many :products
  has_many :sources
end

class Source < ApplicationRecord
  belongs_to :ingredient
end

app/models/product.rb
class Product < ApplicationRecord
  has_and_belongs_to_many :ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def index
  end
  
  def show
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    product = Product.find(params[:id])
    @product = ProductsPresenter.new(product)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/companies/index.html.erb
<h1>Companies#index</h1>
<p>Find me in app/views/companies/index.html.erb</p>

<a href="/companies/1/products">Neutrogena</a>

app/views/ingredients/index.html.erb
<h1>Ingredients#index</h1>
<p>Find me in app/views/ingredients/index.html.erb</p>

app/views/ingredients/show.html.erb
<div class='product-wrapper'>
  <div class='list-item-information'>
    <div class=''><%= @ingredient.name %></div>
    <div class=''><%= @ingredient.description %></div>
    <div class=''><%= @ingredient.main_purpose %></div>
    <div class=''><%= @ingredient.verdict %></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IngridentDb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;300;400;700&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<ul class="list-group">
  <% @products.each do |product| %>
    <li class="list-group-item">
      <%= link_to product_path(product.id), class: "clickable-item" do %>
        <div class="image-wrapper">
          <img class='list-item-image' src=<%= asset_path(product.picture) %> />
        </div>
        <div class='list-item-information'>
          <div class='name'><%= product.name %></div>
          <div class='company'><%= product.company %></div>
          <div class='price'><%= number_to_currency(product.price) %></div>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/products/show.html.erb
<div class='product-wrapper'>
  <div class="image-wrapper">
    <img class='' src=<%= asset_path(@product.picture) %> />
  </div>
  <div class='list-item-information'>
    <div class='name'><%= @product.name %></div>
    <div class='company'><%= @product.company %></div>
    <div class='price'><%= number_to_currency(@product.price) %></div>
    <%= link_to "Buy Online", @product.buy_online, class: 'btn btn-primary buy-now', target: '_blank' %>

    <div class='ingredient-section'>
      <span class='title'>Ingredients</span>
      <div class='legend'>
        <div class='neutral'>Neutral</div>
        <div class='bad'>Bad</div>
        <div class='okay'>Okay</div>
        <div class='good'>Good</div>
      </div>
      <div class='ingredient-list'>
      <% @product.ingredients.each do |ingredient| %>
        <%= link_to ingredient.name, ingredient_path(ingredient.id), class: "rating-#{ingredient.rating_label}" %>,
      <% end %>
      </div>
    </div>
  </div>
</div>